//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beeswarm_timer_v3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingOverlayMode {
            get {
                return ((bool)(this["SettingOverlayMode"]));
            }
            set {
                this["SettingOverlayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asdasd {
            get {
                return ((string)(this["asdasd"]));
            }
            set {
                this["asdasd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int Stockingstime {
            get {
                return ((int)(this["Stockingstime"]));
            }
            set {
                this["Stockingstime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5400")]
        public int SnowbearTime {
            get {
                return ((int)(this["SnowbearTime"]));
            }
            set {
                this["SnowbearTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7200")]
        public int SnowcanonTime {
            get {
                return ((int)(this["SnowcanonTime"]));
            }
            set {
                this["SnowcanonTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5400")]
        public int BeesmasFeastTime {
            get {
                return ((int)(this["BeesmasFeastTime"]));
            }
            set {
                this["BeesmasFeastTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14400")]
        public int CandlesTime {
            get {
                return ((int)(this["CandlesTime"]));
            }
            set {
                this["CandlesTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public int WreathTime {
            get {
                return ((int)(this["WreathTime"]));
            }
            set {
                this["WreathTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int WealthTime {
            get {
                return ((int)(this["WealthTime"]));
            }
            set {
                this["WealthTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public int KickTime {
            get {
                return ((int)(this["KickTime"]));
            }
            set {
                this["KickTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public int MondoTimeMinute {
            get {
                return ((int)(this["MondoTimeMinute"]));
            }
            set {
                this["MondoTimeMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Puffshroom15minute {
            get {
                return ((int)(this["Puffshroom15minute"]));
            }
            set {
                this["Puffshroom15minute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int Puffshroom45minute {
            get {
                return ((int)(this["Puffshroom45minute"]));
            }
            set {
                this["Puffshroom45minute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\stockings.wav\\\\\"")]
        public string StockingsAlertURL {
            get {
                return ((string)(this["StockingsAlertURL"]));
            }
            set {
                this["StockingsAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\snowbear.wav\\\\\"")]
        public string SnowbearAlertURL {
            get {
                return ((string)(this["SnowbearAlertURL"]));
            }
            set {
                this["SnowbearAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\snowcanon.wav\\\\\";")]
        public string SnowcanonAlertURL {
            get {
                return ((string)(this["SnowcanonAlertURL"]));
            }
            set {
                this["SnowcanonAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\beesmas feast.wav\\\\\";")]
        public string FeastAlertURL {
            get {
                return ((string)(this["FeastAlertURL"]));
            }
            set {
                this["FeastAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\Candles.wav\\\\\";")]
        public string CandlesAlertURL {
            get {
                return ((string)(this["CandlesAlertURL"]));
            }
            set {
                this["CandlesAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\wreath.wav\\\\\";")]
        public string WreathAlertURL {
            get {
                return ((string)(this["WreathAlertURL"]));
            }
            set {
                this["WreathAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\wealth clock.wav\\\\\"")]
        public string WealthAlertURL {
            get {
                return ((string)(this["WealthAlertURL"]));
            }
            set {
                this["WealthAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\you should move.wav\\\\\"")]
        public string KickAlertURL {
            get {
                return ((string)(this["KickAlertURL"]));
            }
            set {
                this["KickAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\mondo.wav\\\\\"")]
        public string MondoAlertURL {
            get {
                return ((string)(this["MondoAlertURL"]));
            }
            set {
                this["MondoAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\puffshrooms.wav\\\\")]
        public string PuffshroomsAlertURL {
            get {
                return ((string)(this["PuffshroomsAlertURL"]));
            }
            set {
                this["PuffshroomsAlertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Volume {
            get {
                return ((int)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7200")]
        public int tenbeesMMtime {
            get {
                return ((int)(this["tenbeesMMtime"]));
            }
            set {
                this["tenbeesMMtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14400")]
        public int fiveteenbeesMMtime {
            get {
                return ((int)(this["fiveteenbeesMMtime"]));
            }
            set {
                this["fiveteenbeesMMtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28800")]
        public int thirtyfivebeesMMtime {
            get {
                return ((int)(this["thirtyfivebeesMMtime"]));
            }
            set {
                this["thirtyfivebeesMMtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28800")]
        public int NightMMtime {
            get {
                return ((int)(this["NightMMtime"]));
            }
            set {
                this["NightMMtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\tenbeesMMready.wav\\\\\";")]
        public string tenbeesMMalertURL {
            get {
                return ((string)(this["tenbeesMMalertURL"]));
            }
            set {
                this["tenbeesMMalertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\fiveteenbeedMMready.wav\\\\\";")]
        public string fiveteenbeesMMalertURL {
            get {
                return ((string)(this["fiveteenbeesMMalertURL"]));
            }
            set {
                this["fiveteenbeesMMalertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\thirtyfivebeesMMready.wav\\\\\";")]
        public string thirtyfivebeesMMalertURL {
            get {
                return ((string)(this["thirtyfivebeesMMalertURL"]));
            }
            set {
                this["thirtyfivebeesMMalertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application.StartupPath + \"\\\\sounds\\\\nightmmready.wav\\\\\"")]
        public string NightMMalertURL {
            get {
                return ((string)(this["NightMMalertURL"]));
            }
            set {
                this["NightMMalertURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Einstellung {
            get {
                return ((string)(this["Einstellung"]));
            }
            set {
                this["Einstellung"] = value;
            }
        }
    }
}
